# Generated by Django 3.0.1 on 2020-01-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='oglas',
            name='price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
